INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (1,1,374,'DESKTOP','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (2,1,374,'LAPTOP','SYSTEM B');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (3,1,374,'DESKTOP','SYSTEM C');

INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (4,2,375,'DESKTOP','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (5,2,375,'DESKTOP','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (6,2,375,'DESKTOP','SYSTEM A');

INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (7,3,376,'DESKTOP','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (8,3,376,'desktop','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (9,3,376,'LAPTOP','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (10,3,376,'laptop','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (11,3,376,'LAPTOP','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (12,3,377,'LAPTOP','SYSTEM A');
INSERT INTO USERLICENSE(COMPUTERID,USERID,APPID,COMPUTERTYPE, COMMENTS) VALUES (13,3,376,'laptop','SYSTEM A');

